### ISSUE TITLE
Setting target = NULL

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#2]
https://github.com/ptl93/AEDA/blob/9e66cfdccdc088c157b2d6c4bdafc57d3e6762b3/R/getDataType.R#L16-L17

Why do you check if target is NULL and if it already NULL you set it again NULL?

**Comment by tuanle618** [comment]
yes it was not really needed. I can exclude this line of code.

**Comment by tuanle618** [comment]
@MiGraber  I fixed this issue. If you have time, please have a look into the new version.
