### ISSUE TITLE
Integer are always numerics

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#3]
https://github.com/ptl93/AEDA/blob/9e66cfdccdc088c157b2d6c4bdafc57d3e6762b3/R/getDataType.R#L36-L39

If you first check for numeric und after than for integer you will never get an integer detected because a integer will always be detected as numeric.(all integers are numerics)
If you want to detect an integer you have to swap the order of the checks. First integer and then numeric.

**Comment by tuanle618** [comment]
alright. Will do it later. Thanks for reporting

**Comment by tuanle618** [comment]
@MiGraber  I fixed this issue. If you have time, please have a look into the new version.
