### ISSUE TITLE
Add check for installed packages

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#30]
At the moment packages are loaded via require to prevent loading the same package multiple times.
-> If a package ist not installed user will get error: function foo noz found. So it would be better to check if the package is availabe( installed)  and if not throw a more meaningful error

**Comment by tuanle618** [comment]
should we include all required package in finishReport as import? Then we make sure its installed...

**Comment by MiGraber** [comment]
I would install them only if needed. Else this could get pretty big and the knitting can only be done by the r setup that created it. If we install them via the rmd file then in can be run everywhere.
And the fix ist simple:
https://github.com/ptl93/AEDA/pull/31

**Comment by tuanle618** [comment]
finished #31
