### ISSUE TITLE
Opening tabs for html-tables when executing kable() function in rmd within loop

### ISSUE THREAD

**Issue by tuanle618** [ptl93/AEDA#34]
see Pull-Request #29

**Comment by MiGraber** [comment]
https://github.com/haozhu233/kableExtra/issues/131

Travis is throwing multiple error lines, when knitting:
`Error: GDK_BACKEND does not match available displays`
I assume these errors are related to this issue, but I'm very unsure.
They do not count as failures( during testsing).

**Comment by tuanle618** [comment]
I will investigate this later. I didnt change any default option for the `kable` function and in genereal of viewing the html file which will be created. 
Somehow this only occurs when applying the `kable` function within a `for` loop. In other reports, like numeric summary this somehow does not appear. It might be because we print `contingency` tables and not pure `data.frame` . Will check it out. Thanks for the reminder

**Comment by MiGraber** [comment]
This bug doesn't occour every time I knit the files. Sometimes the tables are shown in the Rstduio viewer tab. So I think this is indeed a bug from kableExtra.

I think GDK_BACKEND error happens when kable tries to show the tables and travis has no "display" to show it. But since travis is passing I would not put to much effort into it, at least for now.

**Comment by tuanle618** [comment]
I fixed the issue. Solution was to create for each contingency table an individual code chunk and then execute the `kable_styling()`. Rather than in one code chunk we loop through all contingency tables but loop within `writeCatSumReport`  through the contingency tables and write code chunks.

**Comment by haozhu233** [comment]
Just noticed that you referenced https://github.com/haozhu233/kableExtra/issues/131. I fixed the bug. Sorry for any inconvenience. :P
