### ISSUE TITLE
Make in-body args to formal-defaults

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#38]
In some functions, like makeClusterAnalysis, there are args which should be accesable for the user (for dbscan method the eps arg) but since they are set fix the user cant override them. If move them to the defaults (functions formals) then there should be freely accesable.
So we should check the functions for such problems.

**Comment by tuanle618** [comment]
You mean in the makeClusterTask, according to the selected `method` we print out the selected parameters ?
Please explain with an code example what you mean.
