### ISSUE TITLE
Add dontrun to examples

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#41]
Some examples are taking quite some time to execute. We should add `\dontrun{}` to them
See: https://stackoverflow.com/a/12038225

Note: Check if this causes a Latex error on Travis

**Comment by tuanle618** [comment]
Which analysis do you have in mind for dontrun?
I believe cluster analysis in general?

**Comment by MiGraber** [comment]
The examples that are listet here:
https://travis-ci.org/ptl93/AEDA/jobs/361092962#L1278-L1284

but since these durations are not very long this has low priority

**Comment by tuanle618** [comment]
Please try this out add the dontrun block on the examples.
